import { GetServerSideProps, NextPage } from 'next'
import Head from 'next/head'

import client from '../../apollo/apolloClient'
import { GET_SINGLE_ARTICLE } from '../../apollo/queries'
import ArticleLayout, {
  ArticleLayoutProps,
} from '../../components/layouts/ArticleLayout'

export const getServerSideProps: GetServerSideProps<ArticleLayoutProps> = async (
  context,
) => {
  const {
    data: { articles },
  } = await client.query({
    query: GET_SINGLE_ARTICLE,
    variables: {
      slug: context.params?.slug,
    },
  })

  const [article] = articles

  return {
    props: {
      article,
    },
  }
}

export const ArticlePage: NextPage<ArticleLayoutProps> = ({ article }) => {
  return (
    <div>
      <Head>
        <title>KawiYuki</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ArticleLayout article={article} />
    </div>
  )
}

export default ArticlePage
